/* Generated by :claw at 2020-02-08T16:50:40.892478Z */

#include <stddef.h>
#include "maxminddb.h"


#if !defined(__CLAW_API)
#  if defined(_WIN32)
#    define __CLAW_API __declspec(dllexport)
#  elif defined(__GNUC__)
#    define __CLAW_API __attribute__((visibility("default")))
#  else
#    define __CLAW_API
#  endif
#endif

#if defined(__cplusplus)
extern C {
#endif

#ifdef _WIN32
#  include <windows.h>
static HMODULE ___claw_module;

static int ___claw_init_wrapper() {
  ___claw_module = GetModuleHandle(NULL);
  return ___claw_module != NULL;
}

static void ___claw_close_wrapper(void) {
}
#else
#  include <dlfcn.h>
static void* ___claw_module;

static int ___claw_init_wrapper() {
  ___claw_module = dlopen(NULL, RTLD_NOW | RTLD_GLOBAL);
  return ___claw_module != NULL;
}

static void ___claw_close_wrapper(void) {
}
#endif

static void* claw_get_proc_addr(const char *name) {
  if(___claw_module == NULL) {
    return NULL;
  }

#ifdef _WIN32
  return (void*) GetProcAddress(___claw_module, name);
#else
  return dlsym(___claw_module, name);
#endif
}

#if defined(__cplusplus)
extern "C" {
#endif

typedef MMDB_lookup_result_s (*__claw_MMDB_lookup_sockaddr_t)(MMDB_s*, struct sockaddr*, int*);
typedef MMDB_lookup_result_s (*__claw_MMDB_lookup_string_t)(MMDB_s*, char*, int*, int*);

static __claw_MMDB_lookup_sockaddr_t __v_claw_MMDB_lookup_sockaddr;
static __claw_MMDB_lookup_string_t __v_claw_MMDB_lookup_string;

__CLAW_API int __claw_bodge_maxminddb_loader_67C8CC1F20A5D833D73E00B66810E1BBB9() {
  if(___claw_init_wrapper()) {

__v_claw_MMDB_lookup_sockaddr = (__claw_MMDB_lookup_sockaddr_t) claw_get_proc_addr("MMDB_lookup_sockaddr");
__v_claw_MMDB_lookup_string = (__claw_MMDB_lookup_string_t) claw_get_proc_addr("MMDB_lookup_string");

    ___claw_close_wrapper();
    return 0;
  }
  return 1;
}


__CLAW_API MMDB_lookup_result_s* __claw_MMDB_lookup_sockaddr(MMDB_lookup_result_s* arg0, MMDB_s* arg1, struct sockaddr* arg2, int* arg3) {
  MMDB_lookup_result_s result = __v_claw_MMDB_lookup_sockaddr(arg1, arg2, arg3);
 (*arg0) = result;
  return arg0;
}

__CLAW_API MMDB_lookup_result_s* __claw_MMDB_lookup_string(MMDB_lookup_result_s* arg0, MMDB_s* arg1, char* arg2, int* arg3, int* arg4) {
  MMDB_lookup_result_s result = __v_claw_MMDB_lookup_string(arg1, arg2, arg3, arg4);
 (*arg0) = result;
  return arg0;
}

#if defined(__cplusplus)
}
#endif
